context:
  version: "1.8.1"

package:
  name: tbox
  version: ${{ version }}

source:
  url: https://github.com/tboox/tbox/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 48284c1f1f6e4e74ce1b4d2447c3141fdfdd3a20ef1cb30fc2f1021149227fdb
  patches:
    - 0001-honor-macosx-deployment-target.patch

build:
  number: 0

requirements:
  run_exports:
    - ${{ pin_subpackage('tbox', upper_bound='x.x') }}
  build:
    - if: unix
      then:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ninja
    - if: win
      then:
        - ${{ compiler('c') }}
        - autotools_clang_conda
        - m2-sed

tests:
  - package_contents:
      include:
        - tbox/*
      lib:
        - tbox
  - script:
      - if: unix
        then:
          - grep -q "TB_CONFIG_MODULE_HAVE_HASH .*1" "$PREFIX/include/tbox/tbox.config.h"
          - grep -q "TB_CONFIG_MODULE_HAVE_CHARSET .*1" "$PREFIX/include/tbox/tbox.config.h"
      - if: win
        then:
          - findstr /R /C:"TB_CONFIG_MODULE_HAVE_HASH .*1" "%LIBRARY_INC%\tbox\tbox.config.h"
          - findstr /R /C:"TB_CONFIG_MODULE_HAVE_CHARSET .*1" "%LIBRARY_INC%\tbox\tbox.config.h"

about:
  homepage: https://tboox.top/?lang=0
  summary: A glib-like multi-platform c library
  description: |
    tbox is a glib-like multi-platform c library. 
  license: Apache-2.0
  license_file: LICENSE.md
  repository: https://github.com/tboox/tbox

extra:
  recipe-maintainers:
    - luadebug
